name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3]
        laravel: [^10.0, ^11.0]
        include:
          - laravel: ^10.0
            testbench: ^8.0
          - laravel: ^11.0
            testbench: ^9.0
    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update --dev
          composer update --prefer-dist --no-interaction --no-progress

      - name: Run tests
        run: composer test
